### ISSUE TITLE
Add camera collisions

### ISSUE THREAD

**Issue by Artharr** [Goutte/godot-trackball-camera#28]
Can you add an option to have camera collide with other stuff like walls?

**Comment by Goutte** [comment]
The first thing I'd try would be to add a Collision Shape as child of the Camera.

Since we're [swapping the Transform](https://github.com/Goutte/godot-trackball-camera/blob/master/addons/goutte.camera.trackball/trackball_camera.gd#L506) of the Camera, I don't think it plays very well with collisions.

Perhaps by rewriting the function differently ?
Always setting the angle from the position, and letting the collision engine handle the position (using a Spring around the target, so that the Camera "slides" on walls neatly — means the zoom shenanigans are to be tweaked too) ?

Sadly i have some health, work and money issues to tend to, and I don't have the leisure to try my hand at this.  You're welcome to try and push a merge request, though !

**Comment by Goutte** [comment]
Perhaps there's a simpler way, but dumber : in `apply_contraints()`, check if the new position is in the walls, and if it is, push it out.

Probably inefficient, but perhaps there's a way.
